if (!require("pacman")) install.packages("pacman"); library(pacman) #helps to load packages more efficiently 
pacman::p_load(BiocManager, ggh4x, DT, openxlsx, readxl, rstatix, ggpubr, janitor,ggstatsplot, tidyverse,ggpattern)


# read Data
Data_claudin3 <- read_excel("C:/Users/jhdiaz/Desktop/Lab stuff/GI Data/Claudin-3/Data_claudin3.xlsx")

Data_claudin3$Treatment<-factor(Data_claudin3$Treatment,levels = c("No Treatment","cNLP"))


claudin3_2<-Data_claudin3 %>%
  filter(Treatment=="No Treatment")%>%
  group_by(Ion,Mouse) %>%
  summarise(
    SD=sd(Length),
    Mean=mean(Length)
  )

#order X axis
claudin3_2$Ion<-factor(claudin3_2$Ion,levels = c("Sham","Gamma","Proton","Iron"))

claudin3_2<-as_tibble(claudin3_2)

claudinttest<-claudin3_2%>%
  t_test(Mean~Ion)%>%
  add_xy_position()


ggbarplot(claudin3_2,"Ion","Mean",add="mean_sd",fill="Ion",error.plot = "upper_errorbar")+
  scale_y_continuous(expand = c(0,0), breaks = c(0,25,50,75,100,125),limits = c(0,125))+
  stat_compare_means(label.y.npc = .90,method = "anova",aes(label = paste0("p = ", ..p.format..)))+
  stat_pvalue_manual(claudinttest,hide.ns = TRUE)+
  theme(legend.position = "")+
  fill_palette(palette = "grey")+
  xlab("")+
  ylab("Length(pixel)")+
  font("ylab",face="bold")+
  font("xy.text",color = "black", face = "bold")+
theme(
  axis.title.x = element_text(size=14, face="bold", colour = "black"),    
  axis.title.y = element_text(size=16, face="bold", colour = "black"),    
  axis.text.x = element_text(size=12, face="bold", colour = "black"), 
  axis.text.y = element_text(size=12, face="bold", colour = "black"),
)


ggsave("Claudin3 Results.svg",width=10,height=7)
browseURL("Claudin3 Results.svg")


ggbetweenstats(claudin3_2,"Ion","Mean",p.adjust.method = "none",plot.type = "box")
ggsave("Test.svg",width=10,height=7)
browseURL("Test.svg")



#------------------Treatments--------------------
claudin3_3<-Data_claudin3 %>%
  group_by(Ion,Treatment,Mouse) %>%
  summarise(
    SD=sd(Length),
    Mean=mean(Length)
  )


claudinttest<-claudin3_3%>%
  group_by(Ion)%>%
  t_test(Mean~Treatment)%>%
  add_xy_position(group = 'Treatment',x='Ion')%>%
  add_significance()

claudinttest<-as_tibble(claudinttest)

grouped_ggbetweenstats(claudin3_3,"Ion","Mean",p.adjust.method = "none",plot.type = "box",grouping.var = "Treatment")

options(scipen=100)

claudin3_4<-Data_claudin3 %>%
  group_by(Ion,Treatment) %>%
  summarise(
    SD=sd(Length),
    Mean=mean(Length)
  )

claudin3_4$Ion<-factor(claudin3_4$Ion,levels = c("Sham","Gamma","Proton","Iron"))

p<-ggplot(claudin3_4,aes(Ion,Mean))+
  geom_bar_pattern(aes(fill=Ion,pattern=Treatment),pattern_density=.1,pattern_spacing=.05,stat="identity",position = position_dodge(),color="black")+
  geom_errorbar(aes(fill=Ion,pattern=Treatment,ymin=Mean,ymax=Mean+SD),position = position_dodge(.9),width=.1)+
  scale_y_continuous(expand = c(0,0), breaks = c(0,25,50,75,100,125),limits = c(0,125))+
  stat_pvalue_manual(claudinttest,hide.ns = TRUE,label = "p.signif")+
  fill_palette(palette= c("#cccccc","#ababab","#818181","#333333"))+
  color_palette(palette = c("black","black"))+
  scale_pattern_manual(values=c("none", 'stripe')) +
  xlab("")+
  ylab("Length(pixel)")+
  theme_pubclean()+
  theme(
    legend.position = "right",
    legend.key.size = unit(x = 1,units = "cm"),
      panel.grid.major.y  = element_blank(),
      panel.grid.minor.y = element_blank(),
      panel.grid.major.x=element_blank(),
      axis.line = element_line(),
      axis.title.x = element_text(size=14, face="bold", colour = "black"),    
      axis.title.y = element_text(size=18, face="bold", colour = "black"),    
      axis.text.x = element_text(size=12, face="bold", colour = "black"), 
      axis.text.y = element_text(size=12, face="bold", colour = "black")
  )+
  guides(pattern = guide_legend(override.aes = list(fill = "white")), 
          fill = "none")


ggsave("Claudin3 Treated Results.svg",width=10,height=7)
browseURL("Claudin3 Treated Results.svg")           





                    